[[language]]
name = "rust"
config = { imports.granularity.group = "module", checkOnSave.command = "clippy" }

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "tpp"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "css"
language-server = { command = "css-languageserver", args = [ "--stdio" ] }